config/routes.rb
Rails.application.routes.draw do
  root "reservations#new"
  get 'reservations/new'
  resources :reservations, only: [:new, :create]
  resources :shuttles
    namespace :api do
      resources :shuttles
    end

  namespace :admin do
    root to: "dashboard#index"
    resources :shuttles
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :shuttle
  validates :name, presence: true
  validates :surname, presence: true
  validates :telephone, presence: true
  validates :people, presence: true
end

app/models/shuttle.rb
class Shuttle < ApplicationRecord
  has_many :reservations
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  http_basic_authenticate_with name: "ada", password: "ada2020"
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index
  end
end

app/controllers/admin/shuttles_controller.rb
class Admin::ShuttlesController < Admin::BaseController
  before_action :set_shuttle, only: [:show, :edit, :update, :destroy]

  # GET /shuttles
  # GET /shuttles.json
  def index
    @shuttles = Shuttle.all
  end

  # GET /shuttles/1
  # GET /shuttles/1.json
  def show
  end

  # GET /shuttles/new
  def new
    @shuttle = Shuttle.new
  end

  # GET /shuttles/1/edit
  def edit
  end

  # POST /shuttles
  # POST /shuttles.json
  def create
    @shuttle = Shuttle.new(shuttle_params)

    respond_to do |format|
      if @shuttle.save
        format.html { redirect_to [:admin, @shuttle], notice: 'Shuttle was successfully created.' }
        format.json { render :show, status: :created, location: @shuttle }
      else
        format.html { render :new }
        format.json { render json: @shuttle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shuttles/1
  # PATCH/PUT /shuttles/1.json
  def update
    respond_to do |format|
      if @shuttle.update(shuttle_params)
        format.html { redirect_to [:admin, @shuttle], notice: 'Shuttle was successfully updated.' }
        format.json { render :show, status: :ok, location: @shuttle }
      else
        format.html { render :edit }
        format.json { render json: @shuttle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shuttles/1
  # DELETE /shuttles/1.json
  def destroy
    @shuttle.destroy
    respond_to do |format|
      format.html { redirect_to admin_shuttles_url, notice: 'Shuttle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shuttle
      @shuttle = Shuttle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shuttle_params
      params.require(:shuttle).permit(:name, :company, :max_people, :people, :time)
    end
end

app/controllers/api/shuttles_controller.rb
class Api::ShuttlesController < ApplicationController
  before_action :set_shuttle,  only: [:show]

  def index
    render json: Shuttle.all
  end

  def show
    render json: @shuttle
  end

  private

  def set_shuttle
    @shuttle = Shuttle.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  include HTTParty
  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      @reservation.shuttle.update(people: @reservation.shuttle.people + @reservation.people)
      response = HTTParty.post('https://hackathon.tim.it/sms/mt',
      headers:{
         "apikey": Rails.application.credentials.tim_api,
         "Content-Type": "application/json",
       },
      body: {
          "address": "tel:#{@reservation.telephone}",
          "message": "Prenotazione effettuata a nome di #{@reservation.name} #{@reservation.surname} per la navetta #{@reservation.shuttle.name} all'orario #{@reservation.shuttle.time.strftime("%H:%M")}. Posti prenotati: #{@reservation.people}. Numero prenotazione NR#{rand 2000..6000}"
      }.to_json)
      puts response.body, response.code, response.message, response.headers.inspect
      redirect_to new_reservation_path, notice: 'Grazie per la sua richiesta di prenotazione! Riceverai un sms di conferma della prenotazione'
    else
      flash[:notice] = 'Non è stato possibile prenotare'
      render "new"
    end
  end

  def new
    @reservation = Reservation.new
  end

private
  def reservation_params
    params.require(:reservation).permit(:name, :surname, :shuttle_id, :telephone, :people)
  end
end

app/helpers/api/shuttles_helper.rb
module Api::ShuttlesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/shuttles_helper.rb
module ShuttlesHelper
end

app/views/admin/dashboard/index.html.erb
<%= link_to 'Shuttle', admin_shuttles_path, class:"btn btn-primary" %>

app/views/admin/shuttles/_form.html.erb
<%= form_with(model: [:admin,shuttle], local: true) do |form| %>
  <% if shuttle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shuttle.errors.count, "error") %> prohibited this shuttle from being saved:</h2>

      <ul>
        <% shuttle.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :max_people %>
    <%= form.number_field :max_people, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :people %>
    <%= form.number_field :people, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.time_select :time, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "Invia", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/shuttles/edit.html.erb
<h1>Editing Shuttle</h1>

<%= render 'form', shuttle: @shuttle %>

<%= link_to 'Show', [:admin, @shuttle], class:"btn btn-info" %> |
<%= link_to 'Back', admin_shuttles_path, class:"btn btn-secondary" %>

app/views/admin/shuttles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shuttles</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Company</th>
      <th>Max people</th>
      <th>People</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shuttles.each do |shuttle| %>
      <tr>
        <td><%= shuttle.name %></td>
        <td><%= shuttle.company %></td>
        <td><%= shuttle.max_people %></td>
        <td><%= shuttle.people %></td>
        <td><%= shuttle.time %></td>
        <td><%= link_to 'Show', [:admin,shuttle],class:"btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_admin_shuttle_path(shuttle), class:"btn btn-secondary" %></td>
        <td><%= link_to 'Destroy', [:admin, shuttle], method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shuttle', new_admin_shuttle_path, class:"btn btn-primary" %>

app/views/admin/shuttles/new.html.erb
<h1>New Shuttle</h1>

<%= render 'form', shuttle: @shuttle %>

<%= link_to 'Back', admin_shuttles_path, class:"btn btn-secondary" %>

app/views/admin/shuttles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shuttle.name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @shuttle.company %>
</p>

<p>
  <strong>Max people:</strong>
  <%= @shuttle.max_people %>
</p>

<p>
  <strong>People:</strong>
  <%= @shuttle.people %>
</p>

<p>
  <strong>Time:</strong>
  <%= @shuttle.time %>
</p>
Reservations:
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>People</th>
      <th>Telephone</th>
      <th>Created_at</th>
    </tr>
  </thead>

  <tbody>
    <%@shuttle.reservations.each do |reservation|%>
      <tr>
        <td><%= reservation.name %></td>
        <td><%= reservation.surname %></td>
        <td><%= reservation.people %></td>
        <td><%= reservation.telephone %></td>
        <td><%= reservation.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_admin_shuttle_path(@shuttle), class:"btn btn-secondary" %> |
<%= link_to 'Back', admin_shuttles_path, class:"btn btn-secondary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdaApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reservations/new.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-3"></div>

  <div class="col-md-6">
    <h1>Completa la prenotazione</h1>
    <%= form_with(model: [@reservation], local: true) do |form| %>
      <% if @reservation.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this shuttle from being saved:</h2>

          <ul>
            <% @reservation.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :shuttle_id %>
        <%= form.collection_select :shuttle_id, Shuttle.all, :id, :name, {selected: params[:shuttle_id]}, {class:"form-control"}  %>
      </div>


      <div class="field">
        <%= form.label :name, "*Nome" %>
        <%= form.text_field :name, value: params[:name], class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :surname, "*Cognome" %>
        <%= form.text_field :surname, value: params[:surname], class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :people, "*Numero di posti" %>
        <%= form.number_field :people, value: params[:people], class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :telephone, "*Cellulare. Prefisso nazionale obbligatorio es. +39 " %>
        <%= form.text_field :telephone, value: params[:telephone], class: 'form-control' %>
      </div>




        <%= form.submit 'Invia', class:"btn btn-primary btn-lg btn-block"  %>

    <% end %>

  </div>
</div>